config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  # static pages routes, not connected to models
  # get '/about', to: 'static_pages#about'

  # dynamic routes
  get '/signup', to: 'users#new'
  
  # login routes
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # restful routes
  resources :users, except: [:new]
  # resources :reviews, only: [:create, :destroy]
  resources :products do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
def self.search(search)
  where("lower(name) LIKE ?", "%#{search}%")
end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :content, presence: true
  validates :content, length: { minimum: 1,message: 'Review cannot be blank' }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  before_save { email.downcase! }
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
#relationship

attr_accessor :upd_user
#validation
  validates :name, :email, :phone, :address, presence: true
  validates :email, format: { with: EMAIL_REGEX}
  validates :phone, length: { maximum: 8, message: 'Too long. Maximum 8 characters'}
  validates :address, length: { maximum: 50, message: 'Too long. Maximum 50 characters'}
  validates :password, presence: true, length: { minimum: 5, message: 'Too short. Enter atleast 5 characters'}, unless: :upd_user
  validates :email, uniqueness: {case_sensitive: true}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def require_login
    unless logged_in?
      flash[:danger] = 'You must be logged in to access this section'
      redirect_to root_url
  end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
  
    # code for searching for a product
    if params[:search]
          @products = Product.search(params[:search]).order('created_at DESC')
          if @products.length == 0
            flash[:warning] = "There are no products containing the term(s)"
          end
    else
          @products =Product.all.order('created_at DESC')
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    # respond_to do |format|
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
    # end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
    # end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def find_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :price)
  end

  def check_admin
    if current_user.admin?
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

before_action :find_product
before_action :find_review, only: [:edit, :update, :destroy]

def index
end

def new
end

def create

@review = Review.new(review_params)
@review.product_id = @product.id
@review.user_id = current_user.id

   if @review.save
     flash[:success] = "Review created!"
     redirect_to product_path(@product)
   else
    #  flash[:warning] = "Please enter your review"
     render 'new'
   end
end

def edit

end

def update

  if @review.update(review_params)
    redirect_to product_path(@product)
  else
    render 'edit'
  end
end

def destroy
  @review.destroy
    flash[:success] = "Review deleted"
    redirect_to product_path(@product)
end

private

def find_product
@product = Product.find(params[:product_id])
end

def review_params
  params.require(:review).permit(:content)
end

def find_review
  @review = Review.find(params[:id])
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    # debugger
    if user && user.authenticate(params[:session][:password])
      flash[:success] = 'Success login!'
      log_in(user)
      # Log the user in and redirect to the user's show page.
      redirect_to products_path
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      # debugger
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?

    flash[:info] = 'Bye bye'

    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #set default user based on the id
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #check if already logged in
  before_action :require_login, only: [:show, :edit, :update, :destroy]

  #check if correct user
  # before_action :correct_user, only: [:edit, :update]
  #check if need logout
  # before_action :require_logout, only: [:new]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
     if current_user?(@user) || current_user.admin?
       @user = User.find(params[:id])
       @reviews = @user.reviews.paginate(page: params[:page])

     else
       flash[:danger] = "This is not your login. Do you want to login again?"
       redirect_to root_url
     end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)


      if @user.save
        log_in(@user)
        flash[:success] = 'User was successfully created.'
      redirect_to user_path(@user)
      else
        render 'new'
      end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

      @user.upd_user = true
      if @user.update(user_params)
        flash[:success] = 'User was successfully updated.'
        redirect_to user_path(@user)
      else
      render 'edit'
      end

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone, :address)
    end



  def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
      flash[:danger] = "This is not your login. Do you want to login again?"
      redirect_to root_url
    end
  end

  def require_logout
    if logged_in?
    flash[:warning] = "You must be logged out to create a new user"
    redirect_to(root_url)
  end
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

#Set session with authenticated user
  def log_in(user)
    session[:user_id]=user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
end

def current_user?(user)
  user == current_user
end

def logged_in?
  ! current_user.nil?
  end

def log_out
  session.delete(:user_id) #delete part of the session
  @current_user  = nil
end

# Redirects to stored location (or to the default).


# Stores the URL trying to be accessed.


end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= yield(:title) %> | Redmart App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%flash.each do |message_type, message|%>
     <div class="alert alert-<%= message_type%>"><%=message%></div>
   <%end%>
   <%= render 'partials/header' %>

   <!-- <h1><%#= heading_detail( yield(:heading) ) %></h1> -->
<div class="container">
  <div class="jumbotron">
    <%= yield %>
  </div>
</div>
<%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer container">
  <small>
    Redmart App made by <a href="https://sg.linkedin.com/in/anupama-dhir-0200153">Anupama Dhir</a>
  </small>
  <nav>
    <ul>
      <!-- <li><%#= link_to "About",   about_path %></li> -->
    </ul>
  </nav>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if logged_in? %>
      <%= link_to "Redmart App", products_path, class: 'navbar-brand' %>
        <% else %>
      <%= link_to "Redmart App", root_path, class: 'navbar-brand' %>
    <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">

        <% if logged_in? %>
          <li>
              <%= link_to "Logout", logout_path, method: :delete %>
          </li>
          <li>
          <%= link_to "Profile", user_path(current_user) %>
        </li>
        <% else %>
        <li>
          <%= link_to "Signup", signup_path %>
        </li>
        <li><%= link_to "Log in", login_path %></li>

        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
          <ul class="dropdown-menu">
             <% if current_user.admin? %>
            <li><%= link_to "Add Products", new_product_path %></li>
            <% end %>
              <li><%= link_to "View Products", products_path %></li>
          </ul></li>
          <% if current_user.admin? %>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Users <b class="caret"></b></a>

            <ul class="dropdown-menu">
            <li><%= link_to 'Add Users', signup_path %></li>
             <li><%= link_to "View Users", users_path %></li>

           </ul>
         </li>
          <% end %>
          <% end %>
      </ul>

    </div><!--/.nav-collapse -->

  </div>
</nav>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit "Create Product", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% provide(:title, @product.name) %>
<h1>Editing Product</h1>

<%= form_for(@product) do |f| %>
  

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit "Edit Product", class: "btn btn-primary" %>
  </div>
<% end %>
<%#= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>
<% provide(:title, "Products") %>
<div class="container col-md-4">
<%= form_tag(products_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
<%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
<% end %>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th><strong>Name</strong></th>
      <th><strong>Price</strong></th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr class="active">
        <td class="active"><%= link_to product.name, product_path(product) %></td>
        <td class="active">$<%= product.price %></td>
        <td class="active"><%= link_to 'Show', product %></td>
        <% if current_user.admin? %>
        <td class="active"><%= link_to 'Edit', edit_product_path(product) %></td>
        <td class="active"><%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

  <% if current_user.admin? %>
  <h4><%= link_to 'Add Product', new_product_path %></h4>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>
<% provide(:title, "New Product") %>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr >
      <th><strong>Name</strong></th>
      <th><strong>Price</strong></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>

    <tr class="active">
      <td class="active">
          <%= @product.name %>
      </td>
      <td class="active" >
      $<%= @product.price %>
      </td>
      <td class="active">
        <% if logged_in? %>
        <%= link_to "Add Review", new_product_review_path(@product) %>   <% if current_user.admin? %>|
        <%= link_to 'Edit', edit_product_path(@product) %> |
        <%= link_to 'Delete', product_path(@product), method: :delete, data: { confirm: "Are you sure?"} %>
<% end %>
<% end %>
      </td>
    </tr>

  </tbody>
</table>


<% if logged_in? %>
<h3>Reviews</h3>
<div class="row">
<div class="col-md-8">
  <%= render @product.reviews %>
</div>
</div>
<% end %>
<h4><%= link_to 'Back', products_path %></h4>

app/views/reviews/_form.html.erb
<% provide(:title, "Create Review") %>
<%= form_for([@product, @product.reviews.build]) do |f| %>
<%= error_messages_for :review %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new review...", class: 'form-control' %>
  </div>
    <%= f.submit "Create Review", class:'btn btn-primary'  %>

<% end %>

app/views/reviews/_review.html.erb
<table class="table table-striped table-hover">
  <tbody>
    <tr class="active">
      <td class="active"><%= review.content %></td>
      <td class="active" align="right">
      <% if logged_in? %>

      <% if review.user_id == current_user.id %>
      <%= link_to "Edit", edit_product_review_path(review.product, review) %> |
      <%= link_to "Delete", product_review_path(review.product, review), method: :delete, data: {confirm: "Are you sure?"} %>

      <% end %>

      <% end %>
    </td>
    </tr>
    </tbody>
  </table>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= form_for([@product, @review]) do |f| %>
<%=f.error_messages %>
<%= f.text_area :content %>
  <%= f.submit "Edit Review", class: "btn btn-primary" %>
  <% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="main-form">


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :"Password Confirmation" %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit "Create User", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<h1>Editing User</h1>

<%#= render 'form', user: @user %>

<%= form_for(@user) do |f| %>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <!-- <div class="field">
    <%#= f.label :password %>
    <%#= f.text_field :password %>
  </div> -->

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit "Edit User", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<% if logged_in? %>
  <% provide(:heading, current_user[:name]) %>
<% end %>


<h1>Users</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="active">
        <td class="active"><%= user.name %></td>
        <td class="active"><%= user.email %></td>
        <td class="active"><%= user.phone %></td>
        <td class="active"><%= user.address %></td>
        <td class="active"><%= link_to 'Show', user %></td>
        <td class="active"><%= link_to 'Edit', edit_user_path(user) %></td>
        <td class="active"><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', signup_path %>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<% provide(:heading, @user.name ) %>
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% if logged_in? %>
  <% provide(:heading, current_user[:name]) %>
<% end %>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
<tr class="active">
  <td class="active"><%= @user.name %></td>
  <td class="active"><%= @user.email %></td>
  <td class="active"><%= @user.phone %></td>
  <td class="active"><%= @user.address %></td>
  <td class="active"><%= link_to 'Edit', edit_user_path(@user) %></td>
</tr>
</tbody>
</table>


    <h3>Reviews</h3>
    <div class="row">
    <div class="col-md-8">
    <%= render @user.reviews %>
  </div>
  </div>
    <h4><%= link_to 'Back', products_path %></h4>
  </div>